### ISSUE TITLE
Navigating ROS Agent in Habitat Sim

### ISSUE THREAD

**Issue by frischzenger** [ericchen321/ros_x_habitat#16]
when I ran step 5, it just stuck to:
INFO env making sure agent is subscribed to sensor topics

and when I ran:
`roslaunch launch/rtabmap_mapping.launch`
it just reports:
 /rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set.

 /rgbd_sync: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set.

how to solve it? thanks

**Comment by Atellas23** [comment]
Hey @frischzenger how did you solve this?
