### ISSUE TITLE
Cannot find data/objects/locobot_merged as directory

### ISSUE THREAD

**Issue by jiaomengzhang** [ericchen321/ros_x_habitat#23]
I0320 21:57:56.475400 124840 ManagedFileBasedContainer.h:210] <Object Template>::convertFilenameToPassedExt : Filename : data/objects/locobot_merged changed to proposed object_config.json filename : data/objects/locobot_merged.object_config.json
W0320 21:57:56.475432 124840 AttributesManagerBase.h:301] <Object Template>::loadAllTemplatesFromPathAndExt : Parsing Object Template : Cannot find data/objects/locobot_merged as directory or data/objects/locobot_merged.object_config.json as config file. Aborting parse.

The following error has been reported. I found that it should be a dataset that requires locobot. Could you tell me where to download it

**Comment by shitoujie** [comment]
that can be fixed by `python -m habitat_sim.utils.datasets_download --uids habitat_example_objects locobot_merged /ros_x_habitat/data/objects`
