### ISSUE TITLE
demo instruction

### ISSUE THREAD

**Issue by hpf9017** [ericchen321/ros_x_habitat#5]
Hi,

Do you have some document to run a demo ? @ian-mitchell @ericchen321 @yhymason 

Thank you very much!

**Comment by ericchen321** [comment]
Hi Pengfei, sorry about the delayed reply... I'll upload the instructions over this weekend.

**Comment by ericchen321** [comment]
Hey @hpf9017 I've updated a part of the steps. I don't have the machine at the moment so can't test them myself, so please let us know if you get any errors.

I'll upload the remaining steps in the coming days.

**Comment by hpf9017** [comment]
> Hey @hpf9017 I've updated a part of the steps. I don't have the machine at the moment so can't test them myself, so please let us know if you get any errors.
> 
> I'll upload the remaining steps in the coming days.

ok, thank you very much! I'll have a try @ericchen321

**Comment by hpf9017** [comment]
I can run the Navigating ROS Agent in Habitat Sim, but it doesn't show the scene as habitat sim example.
![Screenshot from 2021-12-15 02-45-31](https://user-images.githubusercontent.com/17041625/146106847-017986d9-08cb-46d2-bca8-59a2f80b7393.png)

does this problem in the picture matter, or what could be the problem? @ericchen321

**Comment by hpf9017** [comment]
@ericchen321 I have solved the problem, and run the demo successfully by
python3 src/scripts/roam_with_joy.py --hab-env-config-path ./configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes.yaml --episode-id -1 --scene-id ./data/scene_datasets/mp3d/2t7WUuJeko7/2t7WUuJeko7.glb2t7WUuJeko7/2t7WUuJeko7.glb

the reason is that I used the wrong --episode-id with 1.

**Comment by marcopremigit** [comment]
> @ericchen321 I have solved the problem, and run the demo successfully by python3 src/scripts/roam_with_joy.py --hab-env-config-path ./configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes.yaml --episode-id -1 --scene-id ./data/scene_datasets/mp3d/2t7WUuJeko7/2t7WUuJeko7.glb2t7WUuJeko7/2t7WUuJeko7.glb
> 
> the reason is that I used the wrong --episode-id with 1.

Hi, if I run this command it outputs:
`  File "/home/marco/catkin_ws/src/ros_x_habitat/src/scripts/roam_with_joy.py", line 2, in <module>
    from src.roamers.joy_habitat_roamer import JoyHabitatRoamer
ModuleNotFoundError: No module named 'src'`
Have you faced this problem?

**Comment by frischzenger** [comment]
> @ericchen321 I have solved the problem, and run the demo successfully by python3 src/scripts/roam_with_joy.py --hab-env-config-path ./configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes.yaml --episode-id -1 --scene-id ./data/scene_datasets/mp3d/2t7WUuJeko7/2t7WUuJeko7.glb2t7WUuJeko7/2t7WUuJeko7.glb
> 
> the reason is that I used the wrong --episode-id with 1.

I want to know if you run this command with rosxhab environment? 
when I run this under rosxhab， it report PyQt5 and PySide2 errors
thanks!

**Comment by ericchen321** [comment]
@frischzenger I'm also running into PyQt5/PySide2 errors and I'm trying to figure out why.

When I was setting up roxshab back in June I didn't have this problem. So I suspect it's due to some later Ubuntu updates (to ROS-related packages).

**Comment by ericchen321** [comment]
@frischzenger I hope you've resolved the issue but in case you have not yet, I just updated the code so it's compatible with the most recent ROS Noetic updates. Also added more detailed instructions on running ROS planner in Habitat Sim in the readme.
